backend:
  name: git-gateway
  branch: main
media_folder: "public/img"
public_folder: "/img"
collections:
  - name: "blog"
    label: "Blog"
    folder: "/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image alt text", name: "imageAlt", widget: "string" }
      - { label: "Blog tag", name: "tag", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "job"
    label: "Job Post"
    folder: "/career"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Job category",
          name: "jobTag",
          widget: "select",
          options:
            [
              "ui",
              "ux",
              "development",
              "consultant",
              "project-engineering",
              "project-management",
              "qa",
              "video-editing",
              "other",
            ],
        }
      - { label: "Job skills (HTML5, CSS3, JS, Java...)", name: "tag", widget: "string" }
      - { label: "Job Type (Remote job, Full time, Part time...)", name: "jobType", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
